# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_search.ipynb.

# %% auto 0
__all__ = ['Search']

# %% ../nbs/00_search.ipynb 4
from Bio import Entrez
import os
from datetime import datetime, timedelta, date
from fastcore.all import *
from typing import Union, Optional
from pydantic import BaseModel, ValidationError, validator

# %% ../nbs/00_search.ipynb 5
from .data import *
from .result import *
from .parser import *

# %% ../nbs/00_search.ipynb 8
class Search(BaseModel):
    """
    Search class to warp the search and results
    """
    search_tag:str = None #Tag to specifiy the search, can be any from pubmed, Defaul: Title/Abstract
    retmax:int = 200 #Maximum number of results to be retrieved
    retmode:str ='xml' #Format of the returned data, options are xml, 
    sort:str='relevance' #Way to sort the results
    mindate:Optional[int] = None #Initial data to be search from, year
    maxdate:Optional[int] = None #Final data to be search from, year
    idlist:Optional[List[int]]
    email:str = None
    api_key:str = None
    
    @validator('search_tag', always=True)
    def validate_search_tag(cls, v):
        if not v:
            v = 'Title/Abstract'
        if v not in SEARCH_TAGS.keys():
            raise ValueError(f'Search tag need to be some of {SEARCH_TAGS.keys()}')
        return SEARCH_TAGS[v]
    
    @validator('email',always=True)
    def validate_email(cls,v ):
        if 'EMAIL' not in os.environ.keys() or 'API_KEY' not in os.environ.keys():
            print(f"you need to add email and api_key to the environment variables")            
            print(f"['EMAIL'] and ['API_KEY']")
            raise EnvironmentError()
        else: 
            return os.environ.get('EMAIL')
        
    @validator('api_key',always=True)
    def validate_api(cls,v ):
        if 'EMAIL' not in os.environ.keys() or 'API_KEY' not in os.environ.keys():
            print(f"you need to add email and api_key to the environment variables")            
            print(f"['EMAIL'] and ['API_KEY']")
            raise EnvironmentError()
        else: 
            return os.environ.get('API_KEY')


# %% ../nbs/00_search.ipynb 9
@patch
def search(
    self:Search,
    query: str, #Query to be search in pubmed
):
    """
    It receive a query to be searched in pubmed and return the handler of the search
    """
    Entrez.email = self.email
    Entrez.api_key = self.api_key
    query = query+self.search_tag
    handle = Entrez.esearch(db='pubmed',
                    sort=self.sort,
                    retmax=self.retmax,
                    retmode=self.retmode,
                    term=query,
                    mindate = self.mindate,
                    maxdate =self. maxdate)
    results = Entrez.read(handle)
    return results['IdList']

# %% ../nbs/00_search.ipynb 13
@patch
def fetch_details(
    self:Search,
    idlist:List[int], #list of pubmedid to be retreived
    ):
    """
    It receive a list of pubmedIds from a search, and retrieve all the details of those publications
    """
    ids = ','.join(idlist)
    handle = Entrez.efetch(db='pubmed',
                           retmode=self.retmode,
                           id=ids)
    results = Entrez.read(handle)
    return results['PubmedArticle']

# %% ../nbs/00_search.ipynb 14
@patch
def results(
    self:Search,
    query:str, #Term to be queried in pubmed
)->Generator[Result, None, None]:
    """
    Method that do the search and retrieve a generator with all the infomration of the articles"""
    id_list = self.search(query)
    articles = self.fetch_details(id_list)
    for article in articles:
        article_dict = parse_paperinfo(article)
        yield Result.parse_obj(article_dict)
